version: "3"

services:

  # https://github.com/dragonflydb/dragonfly/blob/main/contrib/docker/docker-compose.yml
  dragonfly-db:
    container_name: dragonfly-db-dev
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    restart: on-failure
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    ports:
      - "6379:6379"

  # https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml
  next-app:
    container_name: next-app-node
    restart: on-failure

    depends_on:
      - dragonfly-db
    env_file:
      - .env.local
    build:
      context: ./app
      dockerfile: docker/node.Dockerfile
    volumes:
      - ./app/src:/usr/app/src
      - ./app/public:/usr/app/public

    ports:
      - 3000:3000

volumes:
  dragonflydata:
