version: '3'

services:
  # https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: docker/dev.Dockerfile
    env_file:
      - .env.local
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000